const $=id=>document.getElementById(id);
const codes={0:["Clear sky","☀️"],1:["Mainly clear","🌤️"],2:["Partly cloudy","⛅"],3:["Overcast","☁️"],45:["Fog","🌫️"],48:["Fog","🌫️"],51:["Light drizzle","🌦️"],53:["Drizzle","🌦️"],55:["Dense drizzle","🌧️"],61:["Slight rain","🌦️"],63:["Rain","🌧️"],65:["Heavy rain","🌧️"],71:["Slight snow","🌨️"],73:["Snow","🌨️"],75:["Heavy snow","❄️"],80:["Rain showers","🌦️"],81:["Rain showers","🌧️"],82:["Heavy rain showers","⛈️"],95:["Thunderstorm","⛈️"],96:["Thunderstorm + hail","⛈️"],99:["Thunderstorm + hail","⛈️"]};
function info(c){return codes[c]||["Unknown","🌡️"]}
function dateText(s){return new Intl.DateTimeFormat("en-IN",{weekday:"long",day:"numeric",month:"long"}).format(new Date(s))}
function apiUrl(lat,lon){const u=new URL("https://api.open-meteo.com/v1/forecast");u.searchParams.set("latitude",lat);u.searchParams.set("longitude",lon);u.searchParams.set("current","temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m");u.searchParams.set("daily","weather_code,temperature_2m_max,temperature_2m_min");u.searchParams.set("timezone","auto");u.searchParams.set("forecast_days","5");return u}
function render(loc,d){const [condition,icon]=info(d.current.weather_code);$("place").textContent=loc.country?`${loc.name}, ${loc.country}`:loc.name;$("date").textContent=dateText(d.current.time);$("weatherIcon").textContent=icon;$("temperature").textContent=Math.round(d.current.temperature_2m);$("condition").textContent=condition;$("humidity").textContent=Math.round(d.current.relative_humidity_2m)+"%";$("wind").textContent=Math.round(d.current.wind_speed_10m)+" km/h";$("feels").textContent=Math.round(d.current.apparent_temperature)+"°C";$("forecast").innerHTML=d.daily.time.map((day,i)=>{const [c,ic]=info(d.daily.weather_code[i]);const label=new Intl.DateTimeFormat("en-IN",{weekday:"short"}).format(new Date(day+"T12:00:00"));return `<article class="forecast-day"><div class="day">${label}</div><div class="icon">${ic}</div><strong>${Math.round(d.daily.temperature_2m_max[i])}°</strong><small>${Math.round(d.daily.temperature_2m_min[i])}°</small></article>`}).join("");$("currentWeather").classList.remove("hidden");$("forecastSection").classList.remove("hidden")}
async function weather(lat,lon,loc){$("status").textContent="Loading live weather...";const r=await fetch(apiUrl(lat,lon));if(!r.ok)throw Error("Weather request failed.");const d=await r.json();render(loc,d);$("status").textContent="Live weather updated."}
async function search(city){$("status").textContent="Finding city...";const u=new URL("https://geocoding-api.open-meteo.com/v1/search");u.searchParams.set("name",city);u.searchParams.set("count","1");u.searchParams.set("language","en");u.searchParams.set("format","json");const g=await fetch(u);const gd=await g.json();if(!gd.results?.length)throw Error("City not found. Try another city.");const l=gd.results[0];await weather(l.latitude,l.longitude,l)}
$("searchForm").addEventListener("submit",async e=>{e.preventDefault();const c=$("cityInput").value.trim();if(!c){$("status").textContent="Please enter a city name.";return}try{await search(c)}catch(err){$("status").textContent=err.message}});
$("locationBtn").addEventListener("click",()=>{if(!navigator.geolocation){$("status").textContent="Location is not supported.";return}$("status").textContent="Getting your location...";navigator.geolocation.getCurrentPosition(async p=>{try{await weather(p.coords.latitude,p.coords.longitude,{name:"Your Location",country:""})}catch{$("status").textContent="Could not load weather."}},()=>$("status").textContent="Location permission was denied.")});
search("Delhi").catch(()=>{$("status").textContent="Search for a city to get live weather."});